### PR TITLE
Update CONTRIBUTING.md documentation

### PR DESCRIPTION
**Pull request by UTSAVS26**
**Changes Made to `CONTRIBUTING.md`:**

- Improved clarity and readability by enhancing the formatting and structure of the document.
- Added detailed steps for contributing, including clear instructions for forking, branching, and submitting pull requests.
- Emphasized the importance of descriptive pull request titles and adherence to quality standards.
- Provided a structured overview of the repository layout and organization of code snippets.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
Hi @snamjosh , can you please review my first PR for `hacktoberfest2024` and tell me what changes i need to make or it is good.
Thank you for your time.

**Review by SapphicFire — APPROVED** [review]
Looks good to me, thank you

**Comment by UTSAVS26** [comment]
@SapphicFire thank you for approving these changes. Will these changes will be counted in Hacktoberfest? Or I should work on something else more technical?

**Comment by SapphicFire** [comment]
Hacktoberfest does incorporate low-code and no-code contributions such as these so this would be included, but do feel free and welcome to make technical changes as well, this is a safe space and time to do so

**Comment by UTSAVS26** [comment]
> Hacktoberfest does incorporate low-code and no-code contributions such as these so this would be included, but do feel free and welcome to make technical changes as well, this is a safe space and time to do so

Sure, I will work on more technical changes. Thank you for the clarification.

I'm a bit concerned and confused about whether this PR will be counted for Hacktoberfest, as there doesn't seem to be a label added to it. Could you please confirm if it will be included?

Thank you for your time.

**Pull request merged**
