### PR TITLE
Updated how to contribute.md instructions

### PR DESCRIPTION
**Pull request by JBscriptsNow**
Recommending updates to the CONTRIBUTING.md file. Please disregard any other edits in this pull request. Thanks
- JB

Issue: Github does not automatically switch you over the new branch when it is created. 

Including clarification in Step 2 to prevent users from committing updates to the main branch. We ask them to create a new branch, but never instruct them to switch over to that branch. As per Earl's feedback - "This can be averted in the future just by making sure you always create a new branch when working on something new. And specifically, creating a new branch from a clean main branch."

### CODE REVIEW

**Comment by chelming** [comment]
> Please disregard any other edits in this pull request.

Can you either clean up this branch (https://git-scm.com/docs/git-rebase) by doing a git rebase with something like `git rebase -i HEAD~4` and marking those other files as deleted with a `d` and re-push (git push --force) or delete and re-submit this PR so it only contains the things that you would like included?

**Comment by chelming** [comment]
alternatively, you might be able to go to the **Files Changed** [section in github](https://github.com/ServiceNowDevProgram/code-snippets/pull/698/files), select delete, and then re-commit that update
image

**Comment by JBscriptsNow** [comment]
@chelming I was able to delete the file from the Files Changed section in  github. How do I re-commit that update? Let me know if I still need to take any other steps? Thanks.

**Comment by JBscriptsNow** [comment]
@chelming Let me know if I need to make any other updates. Thanks.

**Comment by chelming** [comment]
Hey @JBscriptsNow sorry for the late response. Looks good now.

**Pull request merged**
