### PR TITLE
DeactivateIncAfter90Days.js

### PR DESCRIPTION
**Pull request by pallipoina92**
This script will deactivate all Incidents after 90 Days.

### CODE REVIEW

**Review by am-shakeel — CHANGES_REQUESTED** [review]
Thank you for your contribution. However, it doesn’t comply with our contributing guidelines. As a reminder, the general requirements (as outlined in the [CONTRIBUTING.md file](https://github.com/ServiceNowDevProgram/code-snippets/blob/main/CONTRIBUTING.md)) are the following: follow the folder+subfolder guidelines and include a readme.md file explaining what the code snippet does. Review your contribution against the guidelines and make the necessary adjustments. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

**Comment by pallipoina92** [comment]
Hi Shakeel,

I am really confused with folder + subfolder guide lines and read.me file.
I have provided couple of snippets and all were closed with same comment.

Can I get any help on the correct process as I think I am confused.

Regards,
Sunil

**Comment by am-shakeel** [comment]
Hi @pallipoina92, Here readme.md file is missing, Once you make additional changes, feel free to re-open this Pull Request or create a new one

**Comment by am-shakeel** [comment]
As it already has an existing readme.md file, that's why it's not allowing. Create a new subfolder and add your respective files.

**Pull request closed without merging**
