### PR TITLE
Default value

### PR DESCRIPTION
**Pull request by TechnologistTim**
Contains:
Default Value snippet
Readme

### CODE REVIEW

**Review by SapphicFire — CHANGES_REQUESTED** [review]
Thank you for your contribution. However, it doesn’t comply with our contributing guidelines. As a reminder, the general requirements (as outlined in the [CONTRIBUTING.md file](https://github.com/ServiceNowDevProgram/code-snippets/blob/main/CONTRIBUTING.md)) are the following: follow the folder+subfolder guidelines and include a readme.md file explaining what the code snippet does. Review your contribution against the guidelines and make the necessary adjustments. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

This is not in a sub-folder structure

**Comment by TechnologistTim** [comment]
Where can I contribute it?

**Comment by SapphicFire** [comment]
Hi Tim,

In this case you would choose either an existing folder, like Server Side, or create a new Folder like Dictionary Scripts. Within that top level folder, you'd create another one with a brief name relevant to your script, such as 'Set Default Value from related record' 

This is described in the contributing link too

**Comment by TechnologistTim** [comment]
👍
Tim Dingle reacted via Yahoo Mail 
 
  On Sat, Nov 2, 2024 at 1:34 AM, Astrid ***@***.***> wrote:   


Hi Tim,

In this case you would choose either an existing folder, like Server Side, or create a new Folder like Dictionary Scripts. Within that top level folder, you'd create another one with a brief name relevant to your script, such as 'Set Default Value from related record'

This is described in the contributing link too

**Pull request closed without merging**
