### PR TITLE
Client script for incidents table ro restrict Priority P1, P2 Incidents

### PR DESCRIPTION
**Pull request by Abhishekchowdarapu**
Uploading just the client script.

@Lacah , please let me know if I'm making any mistake while pulling a request.

### CODE REVIEW

**Comment by Lacah** [comment]
Do you want to get this reopened or will you submit a new one?

**Comment by Abhishekchowdarapu** [comment]
I', submitting new one, but when I try to submit new one it is including
previous commits to the new pull request. How can I avoid this? Please
assist

[image: image.png]

**Comment by Abhishekchowdarapu** [comment]
Hi Laszlo,

I just submitted new one, please check
Client script for incidents table #915

I'm wondering whether I'm making a correct pull request or not.

Please assist.

Thanks,
Abhishek

**Comment by Abhishekchowdarapu** [comment]
> Do you want to get this reopened or will you submit a new one?

I want to reopen this.

**Review by Lacah — APPROVED** [review]
Thanks for the changes, I think this will work.

**Comment by Lacah** [comment]
Any reason for closing? :)

**Pull request closed without merging**
