### PR TITLE
Spnegi - Copy Attachment via Script

### PR DESCRIPTION
**Pull request by spnegi**
Hi Team,

This script will help copy attachment from One table to another table.
It can run on any server side scripting.

### CODE REVIEW

**Review by SapphicFire — CHANGES_REQUESTED** [review]
Thank you for your contribution. However, it doesn’t comply with our contributing guidelines. As a reminder, the general requirements (as outlined in the [CONTRIBUTING.md file](https://github.com/ServiceNowDevProgram/code-snippets/blob/main/CONTRIBUTING.md)) are the following: follow the folder+subfolder guidelines and include a readme.md file explaining what the code snippet does. Review your contribution against the guidelines and make the necessary adjustments. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

This snippet replicates functionality described in Docs without enhancing or expanding significantly on the behaviour.

**Comment by spnegi** [comment]
I have updated it.
Please reopen the request

**Comment by SapphicFire** [comment]
You have the permissions to reopen this

**Comment by spnegi** [comment]
Apologise I am not getting an option to reopen this request.only I can
comment on it

**Comment by spnegi** [comment]
How should I open this?

**Comment by SapphicFire** [comment]
Hi there! Can you please share a screenshot of what you see on this PR? I have a button to reopen and comment and this should be the case for you too. Alternatively, you should be able to reopen from the PR list.

image

**Pull request closed without merging**
