### PR TITLE
MVRS Parent Form Interaction

### PR DESCRIPTION
**Pull request by trade12**
Logic to interact with the parent catalog item from within a MRVS

### CODE REVIEW

**Review by earlduque — CHANGES_REQUESTED** [review]
Please be sure to include a readme.md file with your code-snippet as per outlined in the contributing.md file, please also make the code-snippet folder more descriptive than "a code-snippet". You can add additional commits to this pull request to fix this issue. Once done, it can be approved.

Additionally, the subfolder name should be more descriptive to the code snippet, instead of just MRVS

**Review by trade12 — COMMENTED** [review]
Moved to a new sublevel

**Comment by trade12** [comment]
Required changes created

Code Snippet moved to a new subfolder to containerise purpose and readme.md added

**Comment by earlduque** [comment]
Manually fixed folder structure in this commit https://github.com/ServiceNowDevProgram/code-snippets/commit/d4809d9023c81985b4a16e7bfc830e4189333f5f

**Pull request merged**
