### PR TITLE
SCIM payload generator

### PR DESCRIPTION
**Pull request by MartinStoyanoff**
Created a SCIM Payload Generator script include

### CODE REVIEW

**Comment by sandeepd26** [comment]
Hi @MartinStoyanoff ,
Description is missing from this PR.

**Comment by MartinStoyanoff** [comment]
thank you @sandeepd26, now it has.

**Review by SapphicFire — APPROVED** [review]
SCIM? In my Hacktoberfest? 😄 

Looks good to me, well done. Only note is that your usage example doesn't declare the user sys_id variable, but users can address that themselves if you do not choose to update it.

**Review by kmxo — APPROVED** [review]
AD integration is always a challenge to keep everything in sync. 
I liked the methods created to handle Groups. 
Congrats Martin.

**Pull request merged**
