### PR TITLE
Catalog client script mrvs

### PR DESCRIPTION
**Pull request by ishaanshoor**

### CODE REVIEW

**Comment by earlduque** [comment]
Hello @ishaanshoor, your second folder tier should describe what the code snippet does. "MRVS" isn't a description of your code-snippet.

**Comment by ishaanshoor** [comment]
Hi Earl, 

As my code snippet is related to the multi-row variable set, I've just reused the existing MVRS folder which was already present in the repo and had the loopRows.js file.

And, I've added my restrict_multi_row.js file and updated the readme.md file with the description for my script.

Do you still want to me implement a new folder to include only my script and readme file? Please let me know.

**Comment by earlduque** [comment]
@ishaanshoor good point. Go ahead and create a different folder with a more descriptive folder name.

Issue #163 has been opened to correct the existing /MRVS folder

**Comment by ishaanshoor** [comment]
Hi, @earlduque I've updated as advised.  Please approve and merge.

**Pull request merged**
