### PR TITLE
Apbroct202

### PR DESCRIPTION
**Pull request by bird-03**
This script is created to handle all catalog items client scripts

I am not seeing an option to include only file included lately. Please ignore older file from commit.

Thanks

### CODE REVIEW

**Comment by bird-03** [comment]
Not able to delete older file from this current branch commit, can you please help me with ignoring or deleting the previous commit in other branches. 

Have just included one script include file with below 'read me' description that require commit.
This script include is created to handle all catalog items client scripts

Thanks

**Comment by Lacah** [comment]
Abhishek, I do not have access to delete files from your pull request. As this is a recurring issue with your PRs, I recommend you do the following:
1) Sync your forked repository. It appears that you have not done this in a while, which is causing issues:
image
2) Create a brand new new branch
3) Create / commit your relevant files in this new branch

Moving forward, always sync any repository that is forked before creating new branches. This should help fixing your issues.


Closing this PR now.

**Comment by bird-03** [comment]
Hi Laszlo

Thank you so much for response!

Can you help me with sync section How I can do that from browser login?


*Abhishek Pandey*
*+91 7869881249 || ***@***.*** ***@***.***>*

**Comment by Lacah** [comment]
You should see this in your own forked code-snippets repository:
image

Simply click on **Sync fork**. As I mentioned, make sure you do this regularly, but minimum before creating new branches.

**Comment by bird-03** [comment]
Again Many Thanks!

Have created below new PR and pulled the changes. Helpful if you review and
confirm if it's correct as per guidelines to be accepted.

Aphack2023 pr #989

Thanks!

*Abhishek Pandey*
*+91 7869881249 || ***@***.*** ***@***.***>*

**Pull request closed without merging**
