### PR TITLE
Shamma Negi - Parsing excel file in ServiceNow

### PR DESCRIPTION
**Pull request by spnegi**
This excel parser code helps reading the excel file. One can read excel columns and rows via this code. This code helps reading each row and putting validation on excel if required. One can insert or update the records in ServiceNow based on this code.

We can decide base don what column of excel we need to insert or update the record. We can also set the parent vs child relationship based on excel parser.

This is really beneficial when bul data needs to be uploaded in system.

### CODE REVIEW

**Comment by snamjosh** [comment]
Thanks @spnegi  for your submission. It appears that this pull request contains more files than described in the title. Please review and update the pull request to either remove the extra/unintended files or to update the description to be more comprehensive. Ensure your contributions are meaningful and adhere to the project’s standards. [If applicable: You can create a new branch on your forked repository to avoid accidental inclusions of new commits in the future.]. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

**Comment by spnegi** [comment]
I have only 2 files which is related to this branch. See the screenshot:

image

Please reopen this. I dont see button to reopen the pull request

image

**Comment by spnegi** [comment]
Tried reopening it but it didn't work.
Please reopen this

**Comment by snamjosh** [comment]
Problem is in unwanted commits in your pull request.
Files changed section file count should match with commit count. 
Basically, your PR should contain commit which are relevant to the PR.

**Comment by spnegi** [comment]
I could see 2 file changed which is relevant to my PR. Please suggest what
can I do to correct this

**Pull request closed without merging**
