### PR TITLE
Create Send reminders weekly

### PR DESCRIPTION
**Pull request by TVani5**
Consider the scenario of sending remainder approvals weekly. 

Here is the code on the scheduled job that runs daily but sends notification after every week(7 days) based on the due date.

Same code can be applied to any other table, where you to trigger an event or edit a record on weekly basis based on a certain Date field.

### CODE REVIEW

**Comment by kmohit2809** [comment]
This does not follow the contributing guidelines. Please refer the [contributing.md](https://github.com/ServiceNowDevProgram/code-snippets/blob/main/CONTRIBUTING.md) file.

**Comment by kmohit2809** [comment]
Closing this for now. You can reopen the same or create a new once you have gone through the guidelines.

**Comment by TVani5** [comment]
Hi Mohit,

This is my first time participating in Hacktoberfest.

My earlier 4 pulls were rejected.
Tried different approach for the two pull requests submitted this time.

Could you please help with what went wrong, so I can work in that direction.

Thanks & Regards,
Vani

**Comment by kmohit2809** [comment]
Hi Vani,

There are few basic rules which are mentioned in the contributing.md file present on code snippet repository. 
1. Each and every code should have a readme.md file to explain what it does. For eg if you have a code file with name abc.js then it should have a readme.md file as well. So in total two files in your folder.
2. All the files which you add, should be in specific folder based on the code.
3. When you choose a folder from code snippet repo to create the files, inside that you cannot put your files directly, you need to create a subfolder which kind of describes the code in short and then create your code and readme files there.

You can see the below video to understand the folder structure and hierarchy

[hactoberfest PR submission](https://youtu.be/x4Lwp39PsmY?si=UtGoqDNk5rE-oEmf)

**Comment by TVani5** [comment]
Thanks so much Mohit for taking time and explaining.

I could find option to create only file, hence went ahead with it.

I shall go theought the references provided here and shall submit the code
again.

Thanks once again.

Thanks & Regards,
Vani

**Pull request closed without merging**
