### PR TITLE
Adding code snippet for usage of the Array Utils  Unique  method functionality

### PR DESCRIPTION
**Pull request by Irston**
Adding code snippet for usage of the Array Utils  Unique  method functionality.
My first attempt at Hacktoberfest

### CODE REVIEW

**Comment by earlduque** [comment]
@Irston please review https://github.com/ServiceNowDevProgram/code-snippets/blob/main/CONTRIBUTING.md
this pull request does not follow the proper folder structure and is missing a readme.md file.

I will leave this PR open so that you can add additional commits to bring it up to standard.

**Comment by Irston** [comment]
Hey @earlduque , hope i have got the format right this time.
Apologies if this was wrong again, very new to Git

**Comment by earlduque** [comment]
Almost there! ArrayUtils/unique.js this file is still in an incorrect location. Once this file is removed or relocated I can approve the pull request. Thanks @Irston

**Comment by Irston** [comment]
Hey @earlduque , Thank you for being patient with me. I hope I got it right now?

Regards,
Irston

**Pull request merged**
