### PR TITLE
Dev138198 - Two Catalog Client Script created 

### PR DESCRIPTION
**Pull request by bird-03**
The following two catalog client script is added:
1. Set User Field Values on Load 
2. Combine the Catalog variable in the Description field

Thank you!

### CODE REVIEW

**Review by earlduque — CHANGES_REQUESTED** [review]
Hi @bird-03 you have several files included in this Pull Request that are outside of the scope of your PR's description:

- Business Rules/DeleteUserRole/readme.md
- Business Rules/DeleteUserRole/script.js
- Business Rules/Name Change Profile Update/readme.md
- Business Rules/Name Change Profile Update/script.js
- Business Rules/RoleUpdateOnGroupManagerChange/readme.md
- Business Rules/RoleUpdateOnGroupManagerChange/script.js

Did you mean to include these in your PR? If so, then please update Pull Request description. If you meant for these to be in their own PR, then make sure to create a separate branch for them.

**Comment by bird-03** [comment]
Hi @earlduque 

Thanks for your input! 
Q. if I delete these BRs from #561 will it delete from other PR #558 as well?  if yes, then I will leave this as it's.

Though I created these two PRs with the intention in 2 different branches as 'sn_instances/dev138198' and 'dev138198' somehow it shows altogether in one branch here.

Can you please share some references here to change the branch for PR #561?

Thank You!
Abhishek Pandey

**Comment by earlduque** [comment]
Hi @bird-03, now that I know your intent, I will go ahead and approve both these PRs. In the future, for your reference, if you have your Pull Requests on different branches, then you should be fine to delete files from one without affecting the other. In the future, as long as your PR is trying to push to this repo then it won't affect your main branch.

**Comment by bird-03** [comment]
Hi @earlduque 

Sure. I will make note of that. Thank you so much !!!

**Comment by bird-03** [comment]
Hi @earlduque 

Sure. I will make note of that. Thank you so much !!!

**Pull request merged**
