### PR TITLE
Bulk update catalog item images

### PR DESCRIPTION
**Pull request by captainbraddles**
Update to #956. Bulk catalog item image update script. This script allows for the bulk update of catalog item pictures and icons via a fix or background script.

### CODE REVIEW

**Review by kmohit2809 — CHANGES_REQUESTED** [review]
@captainbraddles thanks for your contribution. As per your script I can see that you are updating the same image/icon on multiple catalog items. Could you please update the readme file accordingly.

**Review by captainbraddles — COMMENTED** [review]
Updated readme.md with some further details.

**Comment by captainbraddles** [comment]
Hi @kmohit2809. I've updated the readme as requested to clarify that the sys_id's used can be the same or different and that the images will be updated for all catalog items that are returned in the query.

Cheers,

Brad

**Review by kmohit2809 — APPROVED** [review]
Looks good. Thanks for the modifications.

**Pull request merged**
