### PR TITLE
Shamma Negi- Send Attachment to any Server

### PR DESCRIPTION
**Pull request by spnegi**
This script helps you to copy or place the file at any server.
You need to copy this script and put it into MID Server Script Include this will copy the file from servicenow to server. It can send any file. no restrctions

### CODE REVIEW

**Comment by Lacah** [comment]
Hi Shamma,

Thanks, this is great, but could you please add some more details to the readme.md file regarding how someone should be using this?

Feel free to reopen this PR once done (or send a new PR).

Many thanks!

**Comment by spnegi** [comment]
Please reopen this pull request. I have done the changes in readme.md file.

**Comment by spnegi** [comment]
Hi Lazlo,

Thanks I updated it. Please check now

Regards,
Shamma

**Review by Lacah — APPROVED** [review]

**Comment by Lacah** [comment]
Great, thanks for the quick update!

**Comment by spnegi** [comment]
Hi Laszlo,

Would you mind checking the below as well?

Spnegi - Copy Attachment via Script by spnegi · Pull Request #1247 ·
ServiceNowDevProgram/code-snippets (github.com)
<https://github.com/ServiceNowDevProgram/code-snippets/pull/1247>

Regards,
Shamma

**Pull request merged**
