### PR TITLE
Drawer buttons

### PR DESCRIPTION
**Pull request by stwinkle**
I have created drawer buttons for the portal homepage to enhance the user experience. These buttons provide users with additional options and quick access to links for easy redirection.

### CODE REVIEW

**Review by am-shakeel — CHANGES_REQUESTED** [review]
I can see the already committed PR - https://github.com/ServiceNowDevProgram/code-snippets/pull/191

Thanks for your submission. It appears that this pull request contains more files than described in the title. Please review and update the pull request to either remove the extra/unintended files or to update the description to be more comprehensive. Ensure your contributions are meaningful and adhere to the project’s standards.
You can create a new branch on your forked repository to avoid accidental inclusions of new commits in the future.
Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

**Comment by stwinkle** [comment]
Its a new commit under new folder named: Drawer Button. Its even in a new branch

**Comment by am-shakeel** [comment]
I can see the already committed PR - https://github.com/ServiceNowDevProgram/code-snippets/pull/191

**Comment by am-shakeel** [comment]
Please remove the already committed PR - https://github.com/ServiceNowDevProgram/code-snippets/pull/191

**Pull request closed without merging**
