### PR TITLE
User role

### PR DESCRIPTION
**Pull request by riya-misra-1**
I have created a custom action for a flow to check the role of user who have submitted the request in catalog item

### CODE REVIEW

**Comment by riya-misra-1** [comment]
I have tried it, it was not working in the case when running the flow as a system user.
It is for the case when we want to know the role of user and running the flow as system user. Using gs.getUser()  will give admin role not the actual role of the user.

**Comment by MartinStoyanoff** [comment]
@chelming feel free to take it over

**Review by Lacah — CHANGES_REQUESTED** [review]
@riya-misra-1 I understand your point about running as system user, but I would still encourage you to look at Chris's suggestion regarding the optimization of your query, i.e. including inputs.role as an initial query parameter and limiting your query to 1 result. Thanks.

**Comment by Lacah** [comment]
Closing this for now. Please update your script per the above discussion and reopen this PR or submit a new one, and we'll be happy to approve it! Thanks!

**Pull request closed without merging**
