### PR TITLE
Attach report's as a pdf to notification

### PR DESCRIPTION
**Pull request by Harshuu870**
This pull explains how ServiceNow provides a simple method to embed these reports directly into email notifications by adding a specific line of code in the email body.

### CODE REVIEW

**Comment by Lacah** [comment]
This pull request seems to be copied from a community answer or existing documentation without proper attribution. Contributions should be original, and any referenced work should be properly attributed. Please correct this and ensure the pull request content aligns with the title and description before resubmitting. Closing this for now.

**Comment by Harshuu870** [comment]
Hello Laszlo,

This is not a copied one, Yes like this content is there on ServiceNow
Community but that is wrong solution, and I have tested that and that is
not working.
Below is the screen shot which is available on the Community
[image: image.png]

And the highlighted part is the incorrect syntax and it is not working, I
have struggled and found my own syntax, which I have submitted.

Regards,
Harsh Deep Singh

**Comment by Harshuu870** [comment]
> This pull request seems to be copied from a community answer or existing documentation without proper attribution. Contributions should be original, and any referenced work should be properly attributed. Please correct this and ensure the pull request content aligns with the title and description before resubmitting. Closing this for now.

This is not a copied one, Yes like this content is there on ServiceNow
Community but that is wrong solution, and I have tested that and that is
not working.
Below is the screen shot which is available on the Community
[image: image.png]

And the highlighted part is the incorrect syntax and it is not working, I
have struggled and found my own syntax, which I have submitted.

Regards,
Harsh Deep Singh

**Review by Harshuu870 — COMMENTED** [review]
This is not a copied one, Yes like this content is there on ServiceNow
Community but that is wrong solution, and I have tested that and that is
not working.
Below is the screen shot which is available on the Community
[image: image.png]

And the highlighted part is the incorrect syntax and it is not working, I
have struggled and found my own syntax, which I have submitted.

**Comment by Harshuu870** [comment]
Hello Team i am waiting for the response

**Comment by Harshuu870** [comment]
@snamjosh @Lacah 
I am waiting for the response

**Comment by Harshuu870** [comment]
Hello @snamjosh @Lacah 

I am waiting for the response.

**Comment by Harshuu870** [comment]
Hello @snamjosh @Lacah

I am waiting for the response.

**Comment by Harshuu870** [comment]
Hello Team,

I am waiting for the response over the snippet which I have added.

Please respond.

Regards,
Harsh Deep Singh

**Comment by Lacah** [comment]
This is under review by our extended moderator team.

**Comment by wiz0floyd** [comment]
1. Don't spam comments asking for reviews. It's rude. All of the maintainers are volunteers doing this in addition to their jobs and personal responsibilities. 

2. This pull request does not satisfy the following requirement in the contributing guidelines:

Expanded Snippets: Code snippets reused from the [ServiceNow Documentation](https://docs.servicenow.com/) or [API References](https://developer.servicenow.com/dev.do#!/reference/) are acceptable only if they are expanded in a meaningful way (e.g., with additional context, documentation, or variations). Remember: “QUANTITY IS FUN, QUALITY IS KEY.”

**Pull request closed without merging**
