### PR TITLE
EDMUnifiedSearch

### PR DESCRIPTION
**Pull request by snamjosh**

### CODE REVIEW

**Comment by earlduque** [comment]
I've submitted a pull request to snamjosh:main to show you how it should be structured and formatted. You can either accept the changes or do the changes yourself. It can be approved then.

**Comment by snamjosh** [comment]
Thank You @earlduque . I accepted the changes.Going forward, i will follow your guidelines for all future PRs.

**Comment by earlduque** [comment]
@snamjosh make sure to actually push/merge the pull request into your snamjosh:main branch so that they can show up in this pull request

**Comment by snamjosh** [comment]
@earlduque I merged the pull request into snamjosh:main branch.

**Pull request merged**
