### PR TITLE
Servicenow code snippets

### PR DESCRIPTION
**Pull request by Radhe-Manasa**
Background script to delegate approvals when approver not available

### CODE REVIEW

**Review by Radhe-Manasa — COMMENTED** [review]
I have merged all the files into single branch

**Comment by Radhe-Manasa** [comment]
Merged all the code snippets into One branch

**Comment by niamccash** [comment]
Hi @Radhe-Manasa you have included files in this PR that are also included in your other PR. Could you please create a separate branch for the new items and make sure the PR accurately reflects the new items? 

Your submitted PRs should be organized.

**Review by niamccash — CHANGES_REQUESTED** [review]
Hi @Radhe-Manasa you have included files in this PR that are also included in your other PR. Could you please create a separate branch for the new items and make sure the PR accurately reflects the new items?

Your submitted PRs should be organized.

**Comment by Radhe-Manasa** [comment]
Hello @niamccash 

I cleaned up the branches, can you please review

**Review by niamccash — CHANGES_REQUESTED** [review]
HI @Radhe-Manasa Thank you for organizing your PRs. I see in this one, there are still two copies of Attachment Mandatory/Mandatory Attachment - very similar code/same functionality under two different sections. I don't think both are necessary. Please remove one. 

If you could format the code for the Inactive Records BR and the readme.md file for the Background Script, that would also be appreciated.

**Comment by Radhe-Manasa** [comment]
Hello @niamccash 

Thanks for reviewing.

I made the changes as suggested and updated the Inactive for the BGR.

**Pull request merged**
