### PR TITLE
Remove roles from inactive user

### PR DESCRIPTION
**Pull request by SaiSankar1309**
Background script to remove all roles from an inactive user

### CODE REVIEW

**Comment by SaiSankar1309** [comment]
code snippet : background script to remove all roles from an inactive user

**Comment by kmxo** [comment]
Hello. It appears that this pull request contains more files than described in the title. 
I'll delete them for now but please remove the extra/unintended files within your next contributions.
Thanks for your submission.

**Comment by Saiprethaa** [comment]
Thank you , I am learning it and doing for the first time. I will correct it next time.

**Comment by kmxo** [comment]
Very good. Congratulations and keep up the great work.

**Pull request merged**
