### PR TITLE
Action to trigger the event from flow

### PR DESCRIPTION
**Pull request by Rampriya-S**
Just give the inputs for  an action  the Event name, Record, Parm1 and Parm2  to trigger the notification from the flow.

### CODE REVIEW

**Review by earlduque — CHANGES_REQUESTED** [review]
Please follow the guidelines outlined in the [contributing.md](https://github.com/ServiceNowDevProgram/code-snippets/blob/fb37d86f7b138a7951dd6f1a6f46ed5fb6d1cc98/CONTRIBUTING.md) file:
- all code snippets should have a readme file
- all code snippets must follow the folder+subfolder guidelines.

**Comment by Rampriya-S** [comment]
How to use this flow action:

From any  main flow or sub flow you can trigger this event by giving an inputs as your event name,  record , pram1  and parm2.

How to Test this script:

Create a notification.
From any flow or sub flow select the 'Create and Event' action.
Pass the input as notification name, record,parm1,parm2.
Execute the flow with test record.
You can see the event will trigger your notification.

**Comment by earlduque** [comment]
Note that the changes must be made to the repository itself;

Please follow the guidelines outlined in the [contributing.md](https://github.com/ServiceNowDevProgram/code-snippets/blob/fb37d86f7b138a7951dd6f1a6f46ed5fb6d1cc98/CONTRIBUTING.md) file:

- all code snippets should have a readme file
- all code snippets must follow the folder+subfolder guidelines.

**Comment by earlduque** [comment]
Closing as stale

**Pull request closed without merging**
