### PR TITLE
Check for ethiopian phone number

### PR DESCRIPTION
**Pull request by Haile-08**
# Check for ethiopian country code

Check if a number is from Ethiopia or not

## Change at

```md
CODE-SNIPPETS
├── Regular Expressions
│   ├── Ethiopian Phone Numbers
│          ├── readme.md
│          ├── EthiopianCountryCode.js
```

## Code Added

```js
//Check for ethiopian country code
function isFromEthiopia(phoneNumber) {
  const regex = /^(\+251|0)(9)([0-9]{8})$/;
  return regex.test(phoneNumber);
}

// Example usage
const phoneNumber = "+251912345678"; // Replace with your phone number
const isEthiopianNumber = isFromEthiopia(phoneNumber);

console.log(isEthiopianNumber);
```

## readme.md

```diff
Check for ethiopian country code

check if a number is from ethiopia or not

Usage

import the function
pass the phone number
returns true if ethiopin else false


Example

 +251987456645
 0917654734
```

### CODE REVIEW

**Review by Lacah — CHANGES_REQUESTED** [review]
Than you for your submission and the wonderful description in your pull request!
This is technically a good contribution, but it sounds waay to specific talking only about Ethiopian phone numbers. I understand that this may be a practical example for the regex, but perhaps it would be helpful to mention at least in the readme that the user can use it with any country code (and how to do that).
Thank you!

**Comment by Haile-08** [comment]
should I change this PR to check all country codes on this branch or create a new branch? this is my first ever open source contribution secondly what contribution could you suggest I do next?

**Comment by Lacah** [comment]
I would say it is enough if you explain that this is a generic regex to validate country codes in phone numbers and show an example e.g. Ethiopia. Make it clear in the readme how to change the code accordingly (remember that not everyone is a pro developer and therefore it my not be obvious for every user).

**Comment by Lacah** [comment]
@Haile-08  If you do not have code snippets of your own to contribute with, I encourage you to check out all repositories that we have contributing in Hacktoberfest: https://github.com/ServiceNowDevProgram/Hacktoberfest
Most repositories have a number issues open that can give you an idea for what to contribute with.
Remember to check the readme and contributing files for each repository you would like to contribute to, as there may be significant differences.

Anything submitted until EOB 31 October will still be counted in Hacktoberfest, even if they are only accepted in November!

Thanks a good luck!

**Pull request closed without merging**
